lib/main.dart
#1
- 画像から入力したテキストをテキストフィールドに反映（上書き）
- main.dart
=> [update] #1 画像入力テキストの反映

lib/api_service.dart, lib/main.dart, lib/ui_result.dart
- #22 
- 類題の提示(ラベル表示のみ)
- 特になし
- 特になし
- 数学-文字式を入力しているのに、APIから取得した類題ラベルが以下のようになってしまう
[理科 - 物質のすがた, 理科 - 宇宙の構造, 理科 - 物質の変化, 理科 - 個体宇宙の概観と活動]
=> [update] #21 類題の提示

lib/colors.dart, lib/main.dart
- #2 
- カラーの調整
- ヘルプボタンの関数化
- x
- x
- x
=> [update] #2 色調整ついでにヘルプボタンの関数化

lib/main.dart
- #2 
- 音声入力ボタンを画像フォルダ参照ボタンに変更し、カメラボタンは写真撮影のみに変更
- x
- x
- x
=> [change] #2 音声入力ボタンを画像フォルダ参照ボタンに変更し、カメラボタンは写真撮影のみに変更

android/app/src/main/AndroidManifest.xml, lib/main.dart, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, pubspec.yaml
- #28 
- 画像取り込みを音声入力に変更
- よくわからないファイルが変更されたので確認してほしい。(commitを分けてあります)
- 過去、音声入力をなくして画像取り組みにしたのを元に戻す。
- 実機でのみ動作確認できた。
- エミュレータではGoogleのマイクを使って権限解放してあげるとうまくいくらしいが無理でした。
- まだ画像取り込みは復活させれていない
=> [add] #28 音声入力

lib/ui_chat.dart
- #14 
- chat画面のUI設定
- x
- x
- x
=> [update] #14 chat画面のUI

lib/main.dart
- #28
- カメラボタンと画像参照ボタンで分けていたのを元に戻した
- x
- x
- x
=> [change] #28 音声認識実装に伴うカメラボタンの機能の修正

lib/main.dart
- #39 
- ヘルプダイアログの変更
- ヘルプの文章追加
- x
- x
- 画像とかボタンが分かりやすくなるといいよね
=> [add] #39 ヘルプの文章追加

lib/ui_chat.dart
- x
- アイコンを追加する場所を作成
- x
- x
- x
=> [update] #14 chat画面のUIアイコン追加

lib/ui_result.dart
- #30  #27 
- リザルト画面にアバターを追加
- UIサイズの調整
- x
- x
- x
=> [add] #30 リザルト画面にアバター追加

lib/ui_chat.dart
- #35 
- メッセージ欄が空白になってしまっていた
- x
- x
- x
=> [fix] #14 chat画面のUIメッセージ欄の修正

lib/main.dart
- #46 
- ホーム画面のUIサイズ調整
- x
- x
- x
=> [fix] #46 ホーム画面UIのサイズ調整

lib/ui_chat.dart, lib/ui_result.dart
=> [add] #29 フィードバックテキスト追加

lib/main.dart, lib/ui_chat.dart, lib/ui_result.dart
- #49 
- 各遷移の際のデータの受け渡しを記述
- x
- x
- x
=> [change] #49 データの受け渡し

lib/ui_chat.dart
#14
- gemini特有の出力をなくした
- こちらが説明（教えるフェーズ）するような質問を追加
- ui_chat.dart
=> [update] #14 aiを改良

lib/api_service.dart, lib/main.dart, lib/ui_chat.dart, lib/ui_result.dart
- x
- 21
- 特になし
- 類題周りを完成させたはずです。抜けがなければ。
=> [fix] #21 類題提示の実装

lib/ui_chat.dart
- #2 
- チャットのUIを吹き出しの形に変更
- x
- x
- x
=> [add] #2 チャットのUIを吹き出しの形に変更

lib/tts_service.dart, lib/ui_chat.dart, lib/ui_result.dart, pubspec.yaml
音声読み上げ機能を実装
- #36 音声読み上げ機能の実装
- x
- tts_service.dartを追加し、チャット画面とリザルト画面でAIのメッセージを表示する際に、その内容を読み上げるようにしました。
- チャット画面では、読み上げ中に新しいメッセージを受け取った場合、現在の読み上げを停止して新しいメッセージを読み上げるようにしています。
- x
- 
- x
=> [add]#36 音声読み上げ機能の実装

.gitignore, ios/Flutter/AppFrameworkInfo.plist, ios/Flutter/Release.xcconfig, ios/Podfile, ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, ios/Runner.xcworkspace/contents.xcworkspacedata, ios/Runner/AppDelegate.swift, ios/Runner/Info.plist
#57
- iosでアプリを実行できるようにした
- iosディレクトリ配下にある環境設定ファイルなど
- flutter runコマンドで実機で動くことを確認
=> [add] #57 iosで実行できるようにした

lib/ui_chat.dart, lib/ui_result.dart, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, windows/flutter/generated_plugin_registrant.cc, windows/flutter/generated_plugins.cmake
#36 
- import文のミスを訂正
- ui_chat.dart
- ui_result.dart
=> [fix] #36 importのミスを訂正

lib/main.dart
=> [add] #60 ライセンスを追加

lib/colors.dart, lib/ui_chat.dart, lib/ui_result.dart
- #2 
- チャット画面のUIを変更
- x
- x
- x
=> Add#2 add chat UI

lib/ui_chat.dart, lib/ui_result.dart
- #2 #27 
- リザルト画面のUI追加
- チャット画面のUI修正
- x
- x
- ラベル保存はコメントアウト、現状保存せずに遷移
- 類題はサンプル問題を入れている
=> [fix] #2 フィードバックのUIを追加・チャットのUI修正

lib/main.dart, lib/ui_chat.dart, lib/ui_result.dart
- #49
- リザルトように受け渡し変数の変更
- x
- x
- x
=> Change#49 change something

lib/main.dart, lib/ui_chat.dart, lib/ui_result.dart
- #70
- チャット送信中の待機、名前の表示、色調整
- x
- x
- x
=> [add] #70 チャット送信中の待機、名前の表示、色調整

lib/ui_result.dart, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, pubspec.yaml
-「ホーム画面へ戻る」を押したときにフィードバック画面の画像を端末に保存
=> [add] #29 フィードバック画像を保存

lib/main.dart, lib/ui_chat.dart, lib/ui_result.dart
- #2
- 右上のDEBUGを消す
- チャットの最小幅を設定
- フィードバックのヘッダーを削除
- x
- x
- x
=> [change] #2 各種調整

ios/Podfile.lock, lib/main.dart
#2
- ホーム画面でのテキスト入力の際に，キーボードを閉じるボタンを追加
- main.dart
=> [update] #2 テキスト入力の際，閉じるボタンを追加

lib/api_service.dart, lib/main.dart, lib/ui_chat.dart, lib/ui_result.dart
=> [update] #65 類題提示

lib/ui_chat.dart, lib/ui_chat_basic.dart
=> [fix] #83 apiKeyの修正

lib/colors.dart, lib/main.dart, lib/ui_chat.dart, lib/ui_chat_basic.dart, lib/ui_result.dart, pubspec.yaml
- #86
- ホームにトグルボタンを置き（ヘルプの隣）、モード切替を実装
- モードはSheredPreferencesにて保存
- x
- x
- 現状のモード切替ボタンはテスト用の仮置き
- ベーシックモードへの変更が確認できるよう、背景色のみ変更
=> [add] #86 テスト用モード切替の追加

lib/ui_chat.dart, lib/ui_result.dart, lib/widget_fbsheet.dart
- #82 
- フィードバックシートのwidgetファイル作成
- データ受け渡し
- 保存
- UI調整
=> [add] #82 fbSheet作成

lib/ui_chat_basic.dart
=> [add] #90 basicAIの改良

lib/ui_chat.dart, lib/ui_chat_basic.dart
#88
- geminiのapiKeyを環境変数に隠した
- ui_chat.dart
- ~/.env
- .envファイルを変更しました
=> [add] #88 geminiのapiKeyを隠した

lib/main.dart
=> [delete] #70 ロード画面の削除

lib/main.dart
- #104 
- ベーシックモードとアドバンスモードで説明文を切り替える
- x
- x
- とりあえずできたところまで
=> [update] #104 ベーシックモードとアドバンスモードで説明文を切り替える

lib/main.dart
- #104 
- ホーム画面をプロトタイプのように作成
- 特になし
- 特になし
- フィードバックボタンと全体統計のボタンを作ったので、実装するときにはその場所に記述をお願いします。
=> [update] #104 残りのUI

lib/api_service.dart
- #94 
- api_service.dartのURLの変更
- コレからはpython起動しなくても使える。
- x
- 30分使用しないと再起動が入り、50秒ほどかかるかも？
=> [add] #94 Web Apiの公開に伴う変更

lib/main.dart
- #104 
- 「モード切替」と「使い方」のボタンをベーシックモードではひらがなにしました
- 特になし
- 特になし
=> [update] #104 UIの修正

lib/colors.dart, lib/main.dart, lib/ui_chat.dart, lib/ui_chat_basic.dart
- #104 
- ホームUIの調整
- x
- x
- x
=> [update] #104 ホーム画面のUI調整

lib/colors.dart, lib/main.dart, lib/ui_chat.dart, lib/ui_chat_basic.dart, lib/ui_result.dart, lib/widget_fbsheet.dart
- #83 
- colors.dartにおいて、Basic用のカラーを別クラスで定義
- それに応じて各ページの記述を修正
- x
- x
- x
=> [update] #83 Basic用のカラー作成

lib/main.dart, lib/ui_chat.dart, lib/ui_chat_basic.dart
- #113
- Basicのラベル編集を削除
- 一部UIの修正
- x
- x
- x
=> [change] #113 Basicのラベル編集を削除

lib/colors.dart, lib/main.dart, lib/ui_chat.dart, lib/ui_chat_basic.dart
- #83
- UIサイズ・テキストサイズの拡大
- ？ボタンの追加
- チャットを直前の２個のみ表示し、左右の矢印ボタンで表示するチャットを切り替える形式に変更
- カラーの調整
- x
- x
- x
=> [change] #83 BasicのUI・チャット形式を変更

devtools_options.yaml, lib/ui_chat.dart, lib/ui_chat_basic.dart, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, pubspec.yaml
#92
- sqlの追加
- ui_chat.dart
- sqfliteデータベースの追加
=> [add] #92 sqlの追加

lib/main.dart, lib/ui_fblist.dart, lib/widget_fbsheet.dart
- #117 
- fblist.dartを作成し、フィードバック一覧のUIを作成
- x
- x
- x
=> [add] #117 一覧UI追加

lib/ui_chat.dart, lib/ui_result.dart, lib/widget_fbsheet.dart
- ui_resultからwidget_fbsheetへのデータ受け渡し
- 樹と相談済み
- x
- x
- x
- x
=> [update] ui_resultからfbsheetへの受け渡し

lib/ui_fbdetail, lib/ui_fblist.dart
- #123 
- ui_fblist.dartの不必要な部分を削除
- ui_fbdetail.dartを追加
- x
- x
- ui_fblist.dartに不必要なものがコメントアウト等されているので、必要なければ削除してください
=> [add] 詳細UI追加

lib/main.dart
- #125
- await処理を変更
- 特になし 
- 特になし
- 解決しました
=> [fix] #125 チャット画面への遷移が遅いのを修正

lib/main.dart, lib/ui_fbdetail.dart, lib/ui_fblist.dart
- #123 
- fblist.dartの要約された問題文のボタンを作成
- fbdetailの細かい修正
- x
- x
- データは仮置き
=> Update/#123 make UI

lib/tts_service.dart, lib/ui_result.dart, linux/flutter/generated_plugin_registrant.cc, linux/flutter/generated_plugins.cmake, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, pubspec.yaml, windows/flutter/generated_plugin_registrant.cc, windows/flutter/generated_plugins.cmake
- #103 
- 音声読み上げをvoicevox web APIに変更
- x
- x
- x
=> [fix]#103音声読み上げ機能の変更（WebAPIを使用するよう変更）

lib/ui_chat.dart
#92
- 最初どういう解き方をしたかを削除
- 問題文の要約(summary)を追加
- ui_chat.dart
- sql
=> [update] #92 sqlの構造を変更

lib/main.dart
- #130
- ホーム画面UIのサイズ、テキストサイズを画面サイズ依存にして、フレキシブル対応に
- x
- x
- x
=> [fix] #130 ホーム画面のUIサイズ調整

lib/ui_fblist.dart
#91
- フィルタリング機能のUIを適当に配置
- コンフリクト予防のため関数分けときました
=> [add] #91 フィルターUIを仮置き

lib/main.dart
- #104 
- モード選択のUIを変更
- x
- x
- x
=> [change] #104 モード選択UIの変更

lib/ui_fblist.dart
#91
- フィルター機能を実装
- UIをある程度調整
- UIの色はなるべく揃えました
=> [update] #91 フィルター機能を実装

lib/ui_fblist.dart
- #91
- カラー調整
- フィルタリング部分の表示・非表示を切り替えられるように変更
- ホームに戻るボタンを左上に
- スクロールトップに戻るボタンを右下に
- x
- x
- x
=> [change] #91 フィルタリングUIの変更

lib/ui_chat.dart, lib/ui_fblist.dart
#92
- 教科のデータも全てリストにする
- ui_chat.dart
- SQLの構造は変えてません，保存形式を変更しました
=> [change] #92 教科もリストにする

lib/ui_fblist.dart
=> [update] #91 教科の型変更に伴う更新

lib/ui_fblist.dart, lib/ui_statistics.dart
#92
- sqlデータの読み取り
- ui_statistics.dart
- web上では動かないよ
- デバックしにくいから読み取り部分はコメント化してあるよ
=> [add] #92 sqlデータの読み取り

lib/ui_fblist.dart
- #117 
- 問題文ボタンのsubjectの複数化の適応
=> [update] #117 問題文ボタンのラベル統合

lib/ui_fblist.dart
- #91 
- フィードバックリストUIのサイズ調整
- 各フィードバックのラベル表示は、フィルターのラベル表示を流用し、スクロールは消去した
- x
- x
- x
=> [change] #91 フィードバックリストUIの変更

lib/ui_fblist.dart
- #91
- タイトル、戻るボタンのUIを変更
- 絞り込みUIの位置を変更
- x
- x
- x
=> [change] #91 タイトルUIの変更

lib/main.dart
- #104 
- モード変更ダイアログ内のボタンをなくし、スワイプによる変更を実装
- x
- x
- x
=> [change] #104 スワイプによるモード変更

lib/colors.dart, lib/main.dart, lib/ui_fblist.dart, lib/ui_statistics.dart
- #100
- タイトル部分をフィードバックと共通に
- グラフの色調整
- ホームのレイアウト調整
- x
- x
- x
=> [change] #100 カラー調整

lib/main.dart, pubspec.lock, pubspec.yaml, windows/flutter/generated_plugin_registrant.cc, windows/flutter/generated_plugins.cmake
#145
- 画像編集機能（画面）の追加
- main.dart
- pubspec.yamlなどの環境設定ファイル
=> [add] #145 画像編集機能の追加

lib/main.dart
- #148 
- isBasicModeが未保存の場合に、モード選択ダイアログを表示
- x
- x
- x
=> [add] #148 初回起動時のモード選択

lib/ui_chat_basic.dart
- #150 
- チャット終了時のメッセージ表示を追加
- 表示ダイアログには、アバター、AIからのメッセージ、ホームへ戻るボタンを配置
- x
- x
- x
=> [add] #150 チャット終了時のメッセージ表示を追加

lib/main.dart
- #130
- キーボード表示時にオーバーフローするので、スクロールに戻した
- x
- x
- x
=> [fix] #130 オーバーフロー修正

lib/ui_statistics.dart
- #100 
- UIのサイズ等、各種調整
- x
- x
- x
=> [change] #100 UIのサイズ等調整

lib/ui_chat_basic.dart
=> [update] #89 チャットの改良

lib/ui_result.dart, lib/ui_statistics.dart, pubspec.lock, pubspec.yaml
- #155 
- フィードバックデータから統計を作成して表示するまでの処理を追加
- データ不足の時はデータが足りないと表示
- 実機での動作未確認
- x
- x
- x
=> #155 add statistics process

lib/ui_result.dart
#78
- 類題やフィードバックから新しい問題を生成
- 問題を表示
- ui_result.dart
- 生成AIを使うので少しラグあり
=> [add] #78 新しい問題の提示

lib/ui_fblist.dart
=> [change] #117 UIの微調整

lib/ui_fblist.dart
- #117 
- フィードバック詳細をフィードバック一覧画面に表示し、データベースと対応
- x
- x
- x
=> [update] #117 フィードバック詳細表示

lib/tts_service.dart, lib/ui_chat.dart, lib/ui_chat_basic.dart, lib/ui_result.dart
- x
- x
- チャット画面での音声読み上げするかどうか設定するボタンを追加
- リザルト画面は未実装
- 画面遷移時にいま読み上げているものを停止する機能を追加（動作していないかも）
- x
- x
=> #162 add tts mute

lib/main.dart, pubspec.yaml
- #165 
- キーボードの閉じるボタン実装？
- x
- x
- x
=> [add] #165 キーボードの閉じるボタン実装

lib/ui_chat.dart, lib/ui_chat_basic.dart, pubspec.yaml
- #165
- チャット画面をスクロールビュー内に配置
- basicのチャット終了時ダイアログのサイズを調整
- x
- x
- x
=> [fix] #165 オーバーフロー修正

lib/ui_fblist.dart, lib/widget_fbsheet.dart
- #123 
- フィードバック詳細画面のUIを調整
- x
- x
- x
- 戻るボタン
- リザルト画面での動作確認
=> [update] #123 fb詳細UI調整

lib/ui_fblist.dart
- #170 
- 詳細表示からの戻るボタン遷移先変更
- x
- x
- x
=> [update] #170 詳細ページの戻るボタン

lib/main.dart, lib/ui_chat.dart, lib/ui_chat_basic.dart
=> [fix] #0 レイアウトバグ修正

lib/ui_result.dart
- #175 
- リザルト画面の詳細表示のバグ修正
- x
- x
- x
=> [fix] #175 リザルト画面の詳細表示

lib/ui_fblist.dart
#91
- リセット時にフィルターデータも全解除
- ラベルを選べない時，アラートを表示
=> [update] #91 フィルダリング機能の改良

lib/ui_fblist.dart
- #193
- フィードバック一覧(絞り込みの方)のスクロール外枠に角丸のClipを設定して、中身を角丸に切り抜くように変更
- UIサイズの調整
- x
- x
- 切り抜きにより実現できたため、影は削除していない。UI幅を小さくしてはいるが、見た目の問題で、直接issueには関与していない。
=> [change] #193 外枠で切り抜き

lib/ui_chat_basic.dart, lib/ui_statistics.dart
#195
- basicモード用のSQLを作成
- basicモードで教科を保存
- basicモードの統計画面で，SQLの読み込み
- ui_statistics.dart
- 新たにテーブル作成したのでエラー起こるかも？起こったら教えて
=> [add] #195 basicモード用のデータベースを追加

lib/ui_chat.dart, lib/ui_chat_basic.dart, lib/ui_fblist.dart, lib/widget_fbsheet.dart
- #198
- フィードバックシートの色等調整
- fbsheetへの要約問題文受け渡し
- タイトル部分の要約問題文参照
- 問題全文表示のカラー調整
- フィードバック一覧初期表示の修正
- x
- x
- x
=> [change] #198 フィードバックシートの見た目調整

lib/ui_chat.dart, lib/ui_chat_basic.dart
- #185 
- BasicのメニューUIがオーバーフローしていたので調整
- チャットメニューの問題をやり直すボタンとホームに戻るボタンの位置入れ替え
- ボタンカラー調整
- x
- x
- x
=> [change] #185 BasicのチャットUI調整

lib/ui_chat.dart
#92
- sqlの作成エラーを修正
- ui_chat.dart
=> [fix] #92 sqlの作成エラーを修正

lib/ui_chat.dart, lib/ui_chat_basic.dart
- #205 
- チャット画面での問題文を要約する
- データベースへの保存時に要約していたのを、チャット開始時に要約するように変更
- それに伴い、フィードバック作成時の内容を変更
- ui_chat.dart
- x
- プルリクエストを書いてるときに修正点を見つけたため、commitが分かれてしまいました
=> [update] #205 チャット画面の問題文を要約

lib/ui_fblist.dart
- #209 
- 一覧表示時は_listScrollController
- 詳細表示時は_detailScrollController
- x
- x
- 詳細表示時の上に戻るボタンは必要ないと判断
=> [fix] #209 scrollController

lib/ui_fblist.dart, lib/widget_fbsheet.dart
- #170 
- フィードバック詳細の項目に問題文とラベルを追加
- x
- x
- x
=> [update] #170 fb詳細の問題文項目追加

lib/math_popup.dart
- #200 
- r'をテキストに表示するようにした
- 特になし
- 数式を入力ボタンより
=> [fix] #200 r'の表示

lib/ui_chat.dart, pubspec.lock, pubspec.yaml
#206
- チャット画面にて，tex表示を実装した
- Aiの応答にtex表示をOKするようにした
- main.dart
- pubspec.yaml
=> [add] #206 tex表示

lib/ui_result.dart
- #216 
- fbsheetへsummaryを渡す部分をコンフリクト解消の際に消していたため、再記述
- chatからsummaryを受け取る記述がなかったため、追加
- x
- x
- x
=> [fix] #216 summaryの受取記述

lib/main.dart
- #206
- 問題文の編集において、フォーカス状態により２つのテキストフィールドが切り替わるよう変更
- 非フォーカス時はTex表現に変換されたRichText(チャット画面の変換を流用)
- フォーカス時は今まで同様、通常のTextField
- x
- x
- x
=> [change] #206 非フォーカス時にTex表現で表示

lib/tts_service.dart, lib/ui_statistics.dart
- #213 
- データ不足の時グラフを表示しない（タイトルは表示するようにあとで修正する）
- 表示確認用のダミーデータを追加
- VOICEVOX WebAPIのAPIkey修正
- x
- x
- x
=> #213 improve statistics

lib/ui_chat.dart, lib/utility.dart
#206
- tex表示をclass化
- ui_chat.dart
- utility.dart
=> [add] #206 tex表示をclass化

lib/ui_chat.dart, lib/ui_chat_basic.dart
#205
- 問題分の要約の修正
- ui_chat.dart
=> [update] #205 問題分の要約の修正

lib/ui_chat_basic.dart
=> [update] #205 微修正

lib/ui_chat.dart, lib/ui_fblist.dart
- #210 
- 読み上げ用テキスト変換処理実装
- 仮データ削除
- x
- x
- 読み上げの不備があれば教えてください
=> [add] #120 読み上げ用テキスト変換

lib/ui_fblist.dart
=> [update] #91 フィルター機能の改良

lib/main.dart, lib/ui_chat_basic.dart, lib/ui_fblist.dart, lib/ui_result.dart, lib/utility.dart, lib/widget_fbsheet.dart
#206
- 数式表示を様々な場所に適用
- main.dart
- ui_result.dart
- widget_fbsheet.dart
- TeX表現をするにあたって使用できないプロパティを削除してしまったので，UIがおかしくなるかもしれません
=> [add] #206 数式の表示を様々な場所に適用

lib/ui_chat.dart, lib/ui_chat_basic.dart
- #200
- チャット画面にも数式UIを追加（こちらでは上部に表示）
- x
- x
- x
=> [add] #200 チャット画面にも数式UIを追加

lib/main.dart
- #236
- ラベルを上に詰める処理を追加
- 教科だけでも入力されていれば、完全な未選択より上に詰める
- x
- x
- x
=> [add] #236 ラベルの上詰め処理を追加

lib/ui_fblist.dart
- #170 
- フィードバック一覧にて、SQLからのデータ反映
- ラベルを作成してfeedbackリストに追加
- _initDatabase
- x
- x
=> [update] #170 fb一覧ラベル反映

lib/ui_chat.dart, lib/ui_chat_basic.dart, lib/ui_fblist.dart, lib/widget_fbsheet.dart
- #239 
- チャット画面(basic,advanced)、フィードバック画面(一覧、詳細)、(リザルト画面)の要約問題文に「+」マークを追加
- x
- x
- x
=> [add] #239 「開きそう」感

lib/ui_statistics.dart
- #243
- グラフの色を教科の色と合わせる
- グラフをクリックしたらその教科の問題数を表示する
- x
- x
- x
=> [fix]#243グラフの色を教科の色と合わせる

lib/math_keyboard.dart, lib/ui_chat.dart, lib/utility.dart
#206
- tex表示の微修正
- utility.dart
- ui_chat.dart
- math_keyboard.dart
- texの構文をr''から$$に変更しました
=> [update] #206 tex表示の微修正

lib/ui_chat.dart, lib/ui_chat_basic.dart, lib/ui_fblist.dart
- #210 
- 音声読み上げテキストの修正
- ラベル修正
- x
- x
- x
=> [update] #210 英語のテキスト

lib/ui_chat.dart
- #210 
- 読み上げテキスト変換にて、アスタリスクの処理を修正
- x
- x
- x
=> [fix] #210 アスタリスク

lib/main.dart, pubspec.lock, pubspec.yaml
- #248
- モード選択画面のベーシックの文章にルビふり
=> [add] #248 ルビを振る

lib/ui_statistics.dart
- #250 
- FBデータがないときにすぐ”データなし”と表示されるように変更
- x
- x
- x
=> #250 fix statistics loading

lib/ui_chat.dart, lib/ui_chat_basic.dart, lib/ui_fblist.dart, lib/widget_fbsheet.dart
- #239 
- 問題文を押すときのアイコンを変更
- x
- x
- x
=> [update] #239 アイコン変更

lib/main.dart
=> [add] #248 ベーシックのモード説明を整えた

lib/ui_fblist.dart
- #256
- フィードバック詳細画面に移動する際に上部に戻るボタンを非表示にするよう変更
- x
- x
- x
=> [add] #256 ボタン非表示処理追加

lib/main.dart
- #258 
- ラベル選択において、選択肢からすでに選択されたラベルを削除するように変更
- x
- x
- x
=> [add] #258 ラベル重複禁止

lib/tpSpeechText.dart, lib/ui_chat.dart, lib/ui_chat_basic.dart
- #210 
- toSpeechText.dartを作成し、モジュール化
- 理科の単位、()、$の追加
- x
- x
- 一言コメントの時にも変換できるようにあとでする
=> [update] #210 toSpeechText.dart作成

lib/main.dart, lib/math_keyboard.dart
- #200
- いろいろな数式のボタン追加
- x
- x
- x
=> [add] #200 数式ボタンを増加

lib/main.dart, lib/terms_content.dart, lib/widget_help_dialog.dart, pubspec.lock, pubspec.yaml
- #260 
- 使い方1ページ目の文章変更
- 利用規約にメールアドレス，お問い合わせフォームのリンク追加
- x
- x
- x
=> [fix]#260使い方説明文の変更，利用規約連絡先変更

lib/ui_chat_basic.dart
=> [update] #195 basicモードの保存を修正

lib/ui_chat.dart, lib/ui_chat_basic.dart
- #265 
- x
- besic/advance両方でチャット終了後に音声読み上げするよう修正
- x
- x
=> [fix]#265_FB画面に行くタイミングで音声読み上げするよう修正

lib/math_keyboard.dart
- #200
- オーバーフローを修正
- x
- x
- x
=> [fix] #200 タブサイズの調整

lib/math_keyboard.dart
- #200 
- 説明文の追加
- x
- x
- 現状、basicでもadvanced同様の漢字表記
=> [add] #200 説明文の追加

lib/ui_statistics.dart
- #275 
- basicモード用のSQL文の）が抜けていたので修正
- x
- x
- x
=> [fix]#275basicモードの全体統計が修正されない問題の修正

lib/main.dart, lib/math_keyboard.dart, lib/ui_chat.dart, lib/ui_chat_basic.dart
- #200
- basicモード用の表現を追加
- x
- x
- x
=> [change] #200 basicモード対応

lib/ui_statistics.dart
- #275 
- basic用のグラフ描写処理を追加
- x
- x
- x
=> [fix]#275basicモードの全体統計が表示されない問題の修正2

lib/ui_fblist.dart, lib/widget_fbsheet.dart
- #286 
- Expandedを削除しただけ
- x
- x
- Expandedを削除しただけなので、おそらく問題ないと思います。
- 他のExpanded使用部分も軽く確認しましたが、大丈夫そうだったので該当箇所以外は特に変更していません。
=> [fix] #286 Expanded削除

lib/ui_statistics.dart
- #275
- ドーナツグラフを中心に統計画面UIのサイズを画面幅依存に調整
- ベーシックモードで漢字表記のままのテキストをひらがなに変更
- x
- x
- x
=> [change] #275 統計UIのサイズ調整

lib/main.dart
#292
- 写真をそのまま入力受付
- main.dart
=> [add] #292 写真をそのまま入力受付
